In [24]:
import h5py
import numpy as np
import scipy as scp
import pandas as pd

In [26]:
def read_data(filename: str = None) -> scp.sparse.csr_matrix:
    with h5py.File(filename, "r") as f:
        express_handle = f["exprs"]
        reconstructed_matrix = scp.sparse.csr_matrix((express_handle.get('data'),
                                                      express_handle.get('indices'),
                                                      express_handle.get('indptr')),
                                                     shape=express_handle.get('shape'))

    return reconstructed_matrix

In [31]:
matrix = read_data(filename='../data/adam.h5')

In [34]:
matrix[:10,:10].toarray()

array([[0., 1., 1., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 2., 0., 0., 0.]])

In [6]:
'''
We'll go with the assumption that indices are column indices of non-zero values. Although most papers say it's the
other way around. We'll need to come back to this to double-check we are interpreting things correctly.

'''

with h5py.File('../data/quake_smart_seq2_trachea.h5', 'r') as hd_file:
    cell_names = np.array(hd_file.get('obs_names'))
    gene_names = np.array(hd_file.get('var_names'))
    shape = np.array(hd_file.get('exprs').get('shape'))
    indices = np.array(hd_file.get('exprs').get('indices'))
    data = np.array(hd_file.get('exprs').get('data'))
    indptr = np.array(hd_file.get('exprs').get('indptr'))

In [12]:
#data.shape == indices.shape
max(indptr) == data.shape[0]

True

In [15]:
max(indices)

23339

In [16]:
shape

array([ 1350, 23341])

In [20]:
a = sp.sparse.csr_matrix((5, 5))


(5, 5)

In [22]:
a.toarray()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])